### PR TITLE
Switch from clj-http to http-kit

### LINKED ISSUE #17: Kale cannot connect to Bluemix staging using TLSv1
The Bluemix staging environment was updated to no longer support TLSv1 API calls. This impacts Kale because some versions of java (including IBM Java 1.8) still perform the initial SSL handshake using TLSv1. When this happens, the following error message is returned.

> A call to: https://api.stage1.ng.bluemix.net triggered an unexpected exception: java.io.EOFException: SSL peer shut down incorrectly

One workaround is to just not use a version of java that make this handshake using a newer version. A better solution would be something that can be applied for any version of java (assuming they support newer versions of TLS).

### PR DESCRIPTION
**Pull request by bruceadams**
This fixes #17 by removing the dependency on Apache HttpClient which does not play well with IBM Java and TLS 1.2. Also, reducing our dependencies shrinks the size of our standalone jar by about a quarter, from 7.8Meg to 5.7M.

### CODE REVIEW

File: test/kale/dry_run_test.clj [hunk 1]
```diff
@@ -94,21 +93,3 @@
                     (do (sut/dry-run {}
                                      ["dry-run" "test-file.html"] [])
                         (slurp "converted/test-file.html.json")))))))))
-
-(deftest dry-run-failure
```
Comment (cjgala) [inline test/kale/dry_run_test.clj:98]: Why was this test taken out?

Comment (bruceadams) [reply test/kale/dry_run_test.clj:98]: Because it was hard? (and then I forgot about it) I'll see if I can get it back in there.

Comment (bruceadams) [reply test/kale/dry_run_test.clj:98]: Good call 📢 . I was incorrectly reporting exceptions during `dry_run`, since the exception format changed a little. Getting this test working forced me to face that 😮 .

**Comment by cjgala** [comment]
This looks really great.  Thanks Bruce for digging into this!
